### ISSUE TITLE
strapi question

### ISSUE THREAD

**Issue by peter-kimanzi** [i1d9/strapi_fcm#1]
hello Ian, I'm one of your followers on twitter GitHub and YouTube, i saw that you are very good with strapi, i have a few questions and would really appreciate if you get back to me, my emails are peterkimanzikithumba@gmail.com or kimjayden001@gmail.com 

thank you in advance.

**Comment by i1d9** [comment]
Hi @peter-kimanzi  dm me on twitter [@39394](https://twitter.com/39394)
